import Trait from "../../../models/Trait.js";
import User from "../../../models/User.js";

const users = (traitIds) => [
  { uid: "uid_a1b2c3d4e5f6", username: "alex", name: "Alex Eriksson", firstName: "Alex", lastName: "Eriksson", email: "alex@example.com", picture: "https://i.pravatar.cc/150?u=alex", website: "https://alexeriksson.se", role: "student", education: "Web Developer", setupComplete: true, traitIds: traitIds.slice(0, 5) },
  { uid: "uid_b2c3d4e5f6a1", username: "sara", name: "Sara Lindqvist", firstName: "Sara", lastName: "Lindqvist", email: "sara@example.com", picture: "https://i.pravatar.cc/150?u=sara", website: "https://saralindqvist.design", role: "student", education: "Digital Designer", setupComplete: true, traitIds: traitIds.slice(2, 7) },
  { uid: "uid_c3d4e5f6a1b2", username: "marcus", name: "Marcus Berg", firstName: "Marcus", lastName: "Berg", email: "marcus@example.com", picture: "https://i.pravatar.cc/150?u=marcus", website: "https://spotify.com", role: "organization", organizationName: "Spotify", roleAtCompany: "Engineering Manager", setupComplete: true, traitIds: traitIds.slice(5, 10) },
  { uid: "uid_d4e5f6a1b2c3", username: "emma", name: "Emma Johansson", firstName: "Emma", lastName: "Johansson", email: "emma@example.com", picture: "https://i.pravatar.cc/150?u=emma", website: "https://emmajohansson.com", role: "student", education: "UX Designer", setupComplete: true, traitIds: traitIds.slice(1, 6) },
  { uid: "uid_e5f6a1b2c3d4", username: "oscar", name: "Oscar Nilsson", firstName: "Oscar", lastName: "Nilsson", email: "oscar@example.com", picture: "https://i.pravatar.cc/150?u=oscar", role: "student", education: "Software Engineer", setupComplete: true, traitIds: traitIds.slice(3, 8) },
  { uid: "uid_f6a1b2c3d4e5", username: "lina", name: "Lina Karlsson", firstName: "Lina", lastName: "Karlsson", email: "lina@example.com", picture: "https://i.pravatar.cc/150?u=lina", website: "https://linakarlsson.se", role: "student", education: "Data Scientist", setupComplete: true, traitIds: traitIds.slice(4, 9) },
  { uid: "uid_a2b3c4d5e6f7", username: "viktor", name: "Viktor Larsson", firstName: "Viktor", lastName: "Larsson", email: "viktor@example.com", picture: "https://i.pravatar.cc/150?u=viktor", role: "organization", organizationName: "Klarna", roleAtCompany: "Product Manager", setupComplete: true, traitIds: traitIds.slice(6, 11) },
  { uid: "uid_b3c4d5e6f7a2", username: "mia", name: "Mia Svensson", firstName: "Mia", lastName: "Svensson", email: "mia@example.com", picture: "https://i.pravatar.cc/150?u=mia", website: "https://miasvensson.design", role: "student", education: "Graphic Designer", setupComplete: true, traitIds: traitIds.slice(0, 4) },
  { uid: "uid_c4d5e6f7a2b3", username: "erik", name: "Erik Gustafsson", firstName: "Erik", lastName: "Gustafsson", email: "erik@example.com", picture: "https://i.pravatar.cc/150?u=erik", role: "student", education: "Frontend Developer", setupComplete: true, traitIds: traitIds.slice(7, 12) },
  { uid: "uid_d5e6f7a2b3c4", username: "sofia", name: "Sofia Persson", firstName: "Sofia", lastName: "Persson", email: "sofia@example.com", picture: "https://i.pravatar.cc/150?u=sofia", website: "https://sofiapersson.se", role: "student", education: "Product Designer", setupComplete: true, traitIds: traitIds.slice(2, 6) },
  { uid: "uid_e6f7a2b3c4d5", username: "nils", name: "Nils Andersson", firstName: "Nils", lastName: "Andersson", email: "nils@example.com", picture: "https://i.pravatar.cc/150?u=nils", role: "organization", organizationName: "IKEA", roleAtCompany: "UX Lead", setupComplete: true, traitIds: traitIds.slice(8, 13) },
  { uid: "uid_f7a2b3c4d5e6", username: "julia", name: "Julia Holm", firstName: "Julia", lastName: "Holm", email: "julia@example.com", picture: "https://i.pravatar.cc/150?u=julia", website: "https://juliaholm.com", role: "student", education: "Motion Designer", setupComplete: true, traitIds: traitIds.slice(1, 5) },
  { uid: "uid_a3b4c5d6e7f8", username: "tobias", name: "Tobias Fransson", firstName: "Tobias", lastName: "Fransson", email: "tobias@example.com", picture: "https://i.pravatar.cc/150?u=tobias", role: "student", education: "Backend Developer", setupComplete: true, traitIds: traitIds.slice(9, 14) },
  { uid: "uid_b4c5d6e7f8a3", username: "hanna", name: "Hanna Lindberg", firstName: "Hanna", lastName: "Lindberg", email: "hanna@example.com", picture: "https://i.pravatar.cc/150?u=hanna", website: "https://hannalindberg.se", role: "student", education: "Content Strategist", setupComplete: true, traitIds: traitIds.slice(3, 7) },
  { uid: "uid_c5d6e7f8a3b4", username: "adam", name: "Adam Strand", firstName: "Adam", lastName: "Strand", email: "adam@example.com", picture: "https://i.pravatar.cc/150?u=adam", role: "organization", organizationName: "Volvo", roleAtCompany: "Software Architect", setupComplete: true, traitIds: traitIds.slice(10, 15) },
  { uid: "uid_d6e7f8a3b4c5", username: "frida", name: "Frida Magnusson", firstName: "Frida", lastName: "Magnusson", email: "frida@example.com", picture: "https://i.pravatar.cc/150?u=frida", website: "https://fridamagnusson.com", role: "student", education: "Brand Designer", setupComplete: true, traitIds: traitIds.slice(5, 9) },
  { uid: "uid_e7f8a3b4c5d6", username: "joel", name: "Joel Bergström", firstName: "Joel", lastName: "Bergström", email: "joel@example.com", picture: "https://i.pravatar.cc/150?u=joel", role: "student", education: "DevOps Engineer", setupComplete: true, traitIds: traitIds.slice(11, 16) },
  { uid: "uid_f8a3b4c5d6e7", username: "amanda", name: "Amanda Ek", firstName: "Amanda", lastName: "Ek", email: "amanda@example.com", picture: "https://i.pravatar.cc/150?u=amanda", website: "https://amandaek.design", role: "student", education: "Interaction Designer", setupComplete: true, traitIds: traitIds.slice(4, 8) },
  { uid: "uid_a4b5c6d7e8f9", username: "pontus", name: "Pontus Åberg", firstName: "Pontus", lastName: "Åberg", email: "pontus@example.com", picture: "https://i.pravatar.cc/150?u=pontus", role: "organization", organizationName: "H&M", roleAtCompany: "Tech Lead", setupComplete: true, traitIds: traitIds.slice(12, 17) },
  { uid: "uid_b5c6d7e8f9a4", username: "isabelle", name: "Isabelle Blom", firstName: "Isabelle", lastName: "Blom", email: "isabelle@example.com", picture: "https://i.pravatar.cc/150?u=isabelle", website: "https://isabelleblom.se", role: "student", education: "Visual Designer", setupComplete: true, traitIds: traitIds.slice(6, 10) },
  { uid: "uid_c6d7e8f9a4b5", username: "simon", name: "Simon Nyberg", firstName: "Simon", lastName: "Nyberg", email: "simon@example.com", picture: "https://i.pravatar.cc/150?u=simon", role: "student", education: "Machine Learning Engineer", setupComplete: true, traitIds: traitIds.slice(13, 18) },
  { uid: "uid_d7e8f9a4b5c6", username: "klara", name: "Klara Hedström", firstName: "Klara", lastName: "Hedström", email: "klara@example.com", picture: "https://i.pravatar.cc/150?u=klara", website: "https://klarahedstrom.com", role: "student", education: "Illustrator", setupComplete: true, traitIds: traitIds.slice(7, 11) },
  { uid: "uid_e8f9a4b5c6d7", username: "mattias", name: "Mattias Lindqvist", firstName: "Mattias", lastName: "Lindqvist", email: "mattias@example.com", picture: "https://i.pravatar.cc/150?u=mattias", role: "organization", organizationName: "Ericsson", roleAtCompany: "CTO", setupComplete: true, traitIds: traitIds.slice(14, 19) },
  { uid: "uid_f9a4b5c6d7e8", username: "rebecka", name: "Rebecka Sjögren", firstName: "Rebecka", lastName: "Sjögren", email: "rebecka@example.com", picture: "https://i.pravatar.cc/150?u=rebecka", website: "https://rebeckasjögren.se", role: "student", education: "Typography Designer", setupComplete: true, traitIds: traitIds.slice(8, 12) },
  { uid: "uid_a5b6c7d8e9f0", username: "christoffer", name: "Christoffer Lund", firstName: "Christoffer", lastName: "Lund", email: "christoffer@example.com", picture: "https://i.pravatar.cc/150?u=christoffer", role: "student", education: "iOS Developer", setupComplete: true, traitIds: traitIds.slice(15, 20) },
  { uid: "uid_b6c7d8e9f0a5", username: "malin", name: "Malin Björk", firstName: "Malin", lastName: "Björk", email: "malin@example.com", picture: "https://i.pravatar.cc/150?u=malin", website: "https://malinbjork.design", role: "student", education: "Service Designer", setupComplete: true, traitIds: traitIds.slice(9, 13) },
  { uid: "uid_c7d8e9f0a5b6", username: "henrik", name: "Henrik Sundberg", firstName: "Henrik", lastName: "Sundberg", email: "henrik@example.com", picture: "https://i.pravatar.cc/150?u=henrik", role: "organization", organizationName: "Northvolt", roleAtCompany: "Head of Design", setupComplete: true, traitIds: traitIds.slice(0, 6) },
  { uid: "uid_d8e9f0a5b6c7", username: "johanna", name: "Johanna Wikström", firstName: "Johanna", lastName: "Wikström", email: "johanna@example.com", picture: "https://i.pravatar.cc/150?u=johanna", website: "https://johannawikstrom.com", role: "student", education: "AR/VR Designer", setupComplete: true, traitIds: traitIds.slice(10, 14) },
  { uid: "uid_e9f0a5b6c7d8", username: "patrik", name: "Patrik Engström", firstName: "Patrik", lastName: "Engström", email: "patrik@example.com", picture: "https://i.pravatar.cc/150?u=patrik", role: "student", education: "Android Developer", setupComplete: true, traitIds: traitIds.slice(16, 20) },
  { uid: "uid_f0a5b6c7d8e9", username: "cecilia", name: "Cecilia Nordin", firstName: "Cecilia", lastName: "Nordin", email: "cecilia@example.com", picture: "https://i.pravatar.cc/150?u=cecilia", website: "https://cecilianordin.se", role: "student", education: "Design Researcher", setupComplete: true, traitIds: traitIds.slice(11, 15) },
  { uid: "uid_a6b7c8d9e0f1", username: "bjorn", name: "Björn Axelsson", firstName: "Björn", lastName: "Axelsson", email: "bjorn@example.com", picture: "https://i.pravatar.cc/150?u=bjorn", role: "organization", organizationName: "Scania", roleAtCompany: "VP Engineering", setupComplete: true, traitIds: traitIds.slice(1, 7) },
  { uid: "uid_b7c8d9e0f1a6", username: "elin", name: "Elin Viklund", firstName: "Elin", lastName: "Viklund", email: "elin@example.com", picture: "https://i.pravatar.cc/150?u=elin", website: "https://elinviklund.design", role: "student", education: "Web Designer", setupComplete: true, traitIds: traitIds.slice(12, 16) },
  { uid: "uid_c8d9e0f1a6b7", username: "gustav", name: "Gustav Holmberg", firstName: "Gustav", lastName: "Holmberg", email: "gustav@example.com", picture: "https://i.pravatar.cc/150?u=gustav", role: "student", education: "Systems Developer", setupComplete: true, traitIds: traitIds.slice(17, 20) },
  { uid: "uid_d9e0f1a6b7c8", username: "anna", name: "Anna Söderberg", firstName: "Anna", lastName: "Söderberg", email: "anna@example.com", picture: "https://i.pravatar.cc/150?u=anna", website: "https://annasoderberg.com", role: "student", education: "Creative Director", setupComplete: true, traitIds: traitIds.slice(13, 17) },
  { uid: "uid_e0f1a6b7c8d9", username: "niklas", name: "Niklas Forsberg", firstName: "Niklas", lastName: "Forsberg", email: "niklas@example.com", picture: "https://i.pravatar.cc/150?u=niklas", role: "organization", organizationName: "King", roleAtCompany: "Game Designer", setupComplete: true, traitIds: traitIds.slice(2, 8) },
  { uid: "uid_f1a6b7c8d9e0", username: "petra", name: "Petra Holmqvist", firstName: "Petra", lastName: "Holmqvist", email: "petra@example.com", picture: "https://i.pravatar.cc/150?u=petra", website: "https://petraholmqvist.se", role: "student", education: "Design Lead", setupComplete: true, traitIds: traitIds.slice(14, 18) },
  { uid: "uid_a7b8c9d0e1f2", username: "ludvig", name: "Ludvig Strand", firstName: "Ludvig", lastName: "Strand", email: "ludvig@example.com", picture: "https://i.pravatar.cc/150?u=ludvig", role: "student", education: "Full Stack Developer", setupComplete: true, traitIds: traitIds.slice(3, 9) },
  { uid: "uid_b8c9d0e1f2a7", username: "josefin", name: "Josefin Åström", firstName: "Josefin", lastName: "Åström", email: "josefin@example.com", picture: "https://i.pravatar.cc/150?u=josefin", website: "https://josefinastrom.com", role: "student", education: "Brand Strategist", setupComplete: true, traitIds: traitIds.slice(15, 19) },
  { uid: "uid_c9d0e1f2a7b8", username: "mikael", name: "Mikael Berggren", firstName: "Mikael", lastName: "Berggren", email: "mikael@example.com", picture: "https://i.pravatar.cc/150?u=mikael", role: "organization", organizationName: "Mojang", roleAtCompany: "Creative Director", setupComplete: true, traitIds: traitIds.slice(4, 10) },
  { uid: "uid_d0e1f2a7b8c9", username: "therese", name: "Therese Lindström", firstName: "Therese", lastName: "Lindström", email: "therese@example.com", picture: "https://i.pravatar.cc/150?u=therese", website: "https://thereselindstrom.se", role: "student", education: "Design Systems Engineer", setupComplete: true, traitIds: traitIds.slice(16, 20) },
  { uid: "uid_e1f2a7b8c9d0", username: "rasmus", name: "Rasmus Öberg", firstName: "Rasmus", lastName: "Öberg", email: "rasmus@example.com", picture: "https://i.pravatar.cc/150?u=rasmus", role: "student", education: "Cloud Engineer", setupComplete: true, traitIds: traitIds.slice(5, 11) },
];

export async function seedUsers() {
  const traitDocs = await Trait.find().lean();
  const traitIds = traitDocs.map((d) => d._id.toString());
  const data = users(traitIds);
  await User.insertMany(data);
  console.log(`Seeded ${data.length} users.`);
}
