import Trait from "../../../models/Trait.js";

const traits = [
  { key: "frontend", trait: "Frontend", color: "#E1B640", colorText: "#000000", icebreaker: "What do you enjoy most about working on the part users actually see?" },
  { key: "backend", trait: "Backend", color: "#CDC49B", colorText: "#000000", icebreaker: "What's a problem you've solved that no one ever sees, but you know matters?" },
  { key: "fullstack", trait: "Fullstack", color: "#92AC85", colorText: "#000000", icebreaker: "Which side do you secretly enjoy more?" },
  { key: "web-developer", trait: "Web Developer", color: "#E37475", colorText: "#000000", icebreaker: "How do you stay updated with new tech?" },
  { key: "branding", trait: "Branding", color: "#644E42", colorText: "#FFFFFF", icebreaker: "What brand do you think just gets it?" },
  { key: "ux", trait: "UX", color: "#EBCC99", colorText: "#000000", icebreaker: "What traits do you feel are important for a UX-designer?" },
  { key: "ui", trait: "UI", color: "#F3CBCC", colorText: "#000000", icebreaker: "How would you like others to describe your UI design?" },
  { key: "product-design", trait: "Product Design", color: "#D0B882", colorText: "#000000", icebreaker: "What project are you most proud of?" },
  { key: "motion-design", trait: "Motion Design", color: "#A884DE", colorText: "#000000", icebreaker: "What role do you think movement plays in a good digital experience?" },
  { key: "digital-design", trait: "Digital Design", color: "#8EC1E9", colorText: "#000000", icebreaker: "What excites you about this industry?" },
  { key: "graphic-design", trait: "Graphic Design", color: "#DACD56", colorText: "#000000", icebreaker: "What graphic style fascinates you?" },
  { key: "art-director", trait: "Art Director", color: "#CBF3ED", colorText: "#000000", icebreaker: "What traits do you feel are important for an Art Director?" },
  { key: "digital-content-creator", trait: "Digital Content Creator", color: "#CA8CCF", colorText: "#000000", icebreaker: "What part of a creative project is the most rewarding for you?" },
  { key: "cloud-stack", trait: "Cloud Stack", color: "#D4D4C3", colorText: "#000000", icebreaker: "What's something you found confusing at first but now really enjoy working with?" },
  { key: "scalable", trait: "Scalable", color: "#951F1F", colorText: "#FFFFFF", icebreaker: "When do you plan ahead vs just build?" },
  { key: "clean-code", trait: "Clean Code", color: "#405548", colorText: "#FFFFFF", icebreaker: "One habit that made your code better?" },
  { key: "ownership", trait: "Ownership", color: "#D7D3E4", colorText: "#000000", icebreaker: "What makes you take ownership of something?" },
  { key: "collaboration", trait: "Collaboration", color: "#66A4BD", colorText: "#000000", icebreaker: "Describe a collaboration that stuck with you." },
  { key: "agile", trait: "Agile", color: "#FF9F9F", colorText: "#000000", icebreaker: "What part of agile do you actually enjoy?" },
  { key: "design-systems", trait: "Design Systems", color: "#70B98D", colorText: "#000000", icebreaker: "What part of a design system is the trickiest to get right?" },
  { key: "user-centered", trait: "User-centered", color: "#CDC5DC", colorText: "#000000", icebreaker: "Can a digital product suit every user group?" },
  { key: "business-driven", trait: "Business-driven", color: "#41B4E3", colorText: "#000000", icebreaker: "When do business and user needs align best?" },
  { key: "responsive-design", trait: "Responsive Design", color: "#3E3F75", colorText: "#FFFFFF", icebreaker: "What's a layout that's trickier than it looks?" },
  { key: "performance", trait: "Performance", color: "#E07F6E", colorText: "#000000", icebreaker: "What made you start caring about performance?" },
  { key: "apis", trait: "APIs", color: "#EDEFBA", colorText: "#000000", icebreaker: "What makes an API nice to work with?" },
  { key: "microservices", trait: "Microservices", color: "#7B3D65", colorText: "#FFFFFF", icebreaker: "Split things up or keep it simple?" },
  { key: "databases", trait: "Databases", color: "#0E598A", colorText: "#FFFFFF", icebreaker: "Have you ever changed your mind about how to structure something?" },
  { key: "security", trait: "Security", color: "#D3BC6B", colorText: "#000000", icebreaker: "Can a product be too secure?" },
  { key: "debugging", trait: "Debugging", color: "#843E2D", colorText: "#FFFFFF", icebreaker: "When do you personally start thinking about security in a project?" },
  { key: "html", trait: "HTML", color: "#342F59", colorText: "#FFFFFF", icebreaker: "What's one simple HTML tag that can improve user experience?" },
  { key: "css", trait: "CSS", color: "#EAA750", colorText: "#000000", icebreaker: "Do you design mobile-first or desktop-first?" },
  { key: "javascript", trait: "JavaScript", color: "#E79F9D", colorText: "#000000", icebreaker: "What's something JavaScript surprised you with?" },
  { key: "typescript", trait: "TypeScript", color: "#744749", colorText: "#FFFFFF", icebreaker: "When did TypeScript start \"clicking\" for you?" },
  { key: "react", trait: "React", color: "#ABCC9B", colorText: "#000000", icebreaker: "What's your favorite thing to build in React?" },
  { key: "laravel", trait: "Laravel", color: "#B68B99", colorText: "#000000", icebreaker: "Where do you draw the line between clean code and fast delivery?" },
  { key: "php", trait: "php", color: "#26606A", colorText: "#FFFFFF", icebreaker: "What's one thing you would improve about php?" },
  { key: "csharp", trait: "C#", color: "#DBD56E", colorText: "#000000", icebreaker: "What's the coolest thing you've built with C# so far?" },
  { key: "nodejs", trait: "Node.js", color: "#523249", colorText: "#FFFFFF", icebreaker: "What do you like using Node for?" },
  { key: "python", trait: "Python", color: "#75BAC4", colorText: "#000000", icebreaker: "What do you usually reach for Python to do?" },
  { key: "3d", trait: "3D", color: "#ED7E59", colorText: "#000000", icebreaker: "What would you love to create in 3D if you had more time?" },
  { key: "premiere-pro", trait: "Premiere Pro", color: "#464655", colorText: "#FFFFFF", icebreaker: "What makes an edit feel satisfying to watch?" },
  { key: "indesign", trait: "InDesign", color: "#E0ACD5", colorText: "#000000", icebreaker: "What kind of layouts do you enjoy working on?" },
  { key: "illustrator", trait: "Illustrator", color: "#C9E4EB", colorText: "#000000", icebreaker: "What do you like illustrating when you have free hands?" },
  { key: "photoshop", trait: "Photoshop", color: "#6F1A07", colorText: "#FFFFFF", icebreaker: "How do you know you are finished with a photoshop project?" },
  { key: "dotnet", trait: ".NET", color: "#F1D56F", colorText: "#000000", icebreaker: "What kind of setup do you enjoy working in?" },
  { key: "sql", trait: "SQL", color: "#EE797B", colorText: "#000000", icebreaker: "Queries or data, what do you enjoy more?" },
  { key: "aws", trait: "AWS", color: "#CC9751", colorText: "#000000", icebreaker: "What have you actually used in AWS?" },
  { key: "docker", trait: "Docker", color: "#736579", colorText: "#FFFFFF", icebreaker: "Do you prefer predictable setups or flexible environments?" },
  { key: "ci-cd", trait: "CI/CD", color: "#453C62", colorText: "#FFFFFF", icebreaker: "What's something you've automated that saved you time?" },
  { key: "git", trait: "Git", color: "#BCBCD3", colorText: "#000000", icebreaker: "One Git habit you always stick to?" },
  { key: "after-effects", trait: "After Effects", color: "#F4E87C", colorText: "#000000", icebreaker: "What kind of motion do you enjoy creating the most?" },
  { key: "bold", trait: "Bold", color: "#E47A9B", colorText: "#000000", icebreaker: "Is bold design always the better choice?" },
  { key: "disruptive", trait: "Disruptive", color: "#18B47D", colorText: "#000000", icebreaker: "What's something in your field you think could be done differently?" },
  { key: "empathic", trait: "Empathic", color: "#DADE9E", colorText: "#000000", icebreaker: "Have you ever had a project completely change direction after user feedback?" },
  { key: "emotional", trait: "Emotional", color: "#65532F", colorText: "#FFFFFF", icebreaker: "What's a digital experience that actually made you feel something?" },
  { key: "storytelling", trait: "Storytelling", color: "#AC94B2", colorText: "#000000", icebreaker: "Where do you think storytelling shows up in your work?" },
  { key: "meaningful", trait: "Meaningful", color: "#9D9C62", colorText: "#000000", icebreaker: "What kind of projects feel meaningful to you?" },
  { key: "nextjs", trait: "next.js", color: "#005377", colorText: "#FFFFFF", icebreaker: "What's the number one perk working with next.js?" },
  { key: "figma", trait: "Figma", color: "#FFECD1", colorText: "#000000", icebreaker: "One thing in Figma you use all the time?" },
  { key: "adobe", trait: "Adobe", color: "#F7A072", colorText: "#000000", icebreaker: "Which Adobe tool do you keep coming back to?" },
  { key: "webflow", trait: "Webflow", color: "#D89B6C", colorText: "#000000", icebreaker: "What kind of projects do you think Webflow is perfect for?" },
  { key: "wordpress", trait: "WordPress", color: "#412E8D", colorText: "#FFFFFF", icebreaker: "When is WordPress the better choice?" },
  { key: "framer", trait: "Framer", color: "#853084", colorText: "#FFFFFF", icebreaker: "What's something fun you've experimented with in Framer?" },
  { key: "accessibility", trait: "Accessibility", color: "#31B4A2", colorText: "#000000", icebreaker: "What made you start noticing accessibility more?" },
  { key: "continuous-learning", trait: "Continuous Learning", color: "#8F97D1", colorText: "#000000", icebreaker: "What's something new you've picked up recently?" },
  { key: "facilitative", trait: "Facilitative", color: "#F7C1BB", colorText: "#000000", icebreaker: "How do you get others to share ideas?" },
  { key: "strategic", trait: "Strategic", color: "#582A69", colorText: "#FFFFFF", icebreaker: "What's something you've planned ahead that paid off later?" },
  { key: "user-research", trait: "User Research", color: "#EF789B", colorText: "#000000", icebreaker: "What's a question you like asking users?" },
  { key: "usability-testing", trait: "Usability Testing", color: "#9BAE13", colorText: "#000000", icebreaker: "What's something users did that you didn't expect at all?" },
  { key: "wireframing", trait: "Wireframing", color: "#AA114A", colorText: "#FFFFFF", icebreaker: "When do you move past wireframes?" },
  { key: "prototyping", trait: "Prototyping", color: "#C4C06C", colorText: "#000000", icebreaker: "What do you usually test first in a prototype?" },
  { key: "tech-savvy", trait: "Tech Savvy", color: "#004643", colorText: "#FFFFFF", icebreaker: "What is the coolest tech you've discovered recently?" },
  { key: "information-architecture", trait: "Information Architecture", color: "#C9B7A8", colorText: "#000000", icebreaker: "What's your way of making complex things feel simple?" },
  { key: "innovation", trait: "Innovation", color: "#D08080", colorText: "#000000", icebreaker: "When do you feel most creative in your work?" },
  { key: "adaptable", trait: "Adaptable", color: "#55552C", colorText: "#FFFFFF", icebreaker: "What helps you reset when things suddenly change?" },
  { key: "perfectionist", trait: "Perfectionist", color: "#215E45", colorText: "#FFFFFF", icebreaker: "Does being a perfectionist help or slow you down in creative projects?" },
  { key: "detail-oriented", trait: "Detail-oriented", color: "#F6F0D3", colorText: "#000000", icebreaker: "What's a detail you always notice that others might miss?" },
  { key: "team-player", trait: "Team Player", color: "#C8E5F8", colorText: "#000000", icebreaker: "Working in teams, what is your strength?" },
  { key: "independent", trait: "Independent", color: "#E5B971", colorText: "#000000", icebreaker: "What kind of tasks do you prefer owning completely?" },
  { key: "problem-solving", trait: "Problem-solving", color: "#772845", colorText: "#FFFFFF", icebreaker: "What do you usually do when you get stuck?" },
  { key: "analytical", trait: "Analytical", color: "#643C56", colorText: "#FFFFFF", icebreaker: "When do you trust your gut instead of the data?" },
  { key: "structured", trait: "Structured", color: "#6DAA84", colorText: "#000000", icebreaker: "How do you bring order to chaos?" },
  { key: "communicative", trait: "Communicative", color: "#FFE5A4", colorText: "#000000", icebreaker: "How do you handle feedback?" },
  { key: "proactive", trait: "Proactive", color: "#644C60", colorText: "#FFFFFF", icebreaker: "What's something you started on your own that you're glad you did?" },
  { key: "ai", trait: "AI", color: "#869BBE", colorText: "#000000", icebreaker: "What AI services would you like to design?" },
  { key: "curious", trait: "Curious", color: "#455170", colorText: "#FFFFFF", icebreaker: "What rabbit hole have you gone down recently?" },
  { key: "artistic", trait: "Artistic", color: "#F88DD8", colorText: "#000000", icebreaker: "If you could only pick one tool for creativity, what would it be?" },
  { key: "typography", trait: "Typography", color: "#4A5182", colorText: "#FFFFFF", icebreaker: "What is your typographic security blanket?" },
];

export async function seedTraits() {
  const ops = traits.map((t) => ({
    updateOne: {
      filter: { key: t.key },
      update: { $set: t },
      upsert: true,
    },
  }));
  const result = await Trait.bulkWrite(ops);
  console.log(`Traits seeded: ${result.upsertedCount} inserted, ${result.modifiedCount} updated.`);
  
}
